---
engines:
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG

engines:
  eslint:
    enabled: true

ratings:
  paths: ["lib/jscc.js"]

exclude_paths: ["src/**/*", "test/**/*", "lib/jscc.es.*"]
