language: node_js

node_js:
    - "10"
    - "6.0"

branches:
    only:
        - master
        - dev

git:
    depth: 3
    quiet: true

before_script:
    - setup_cover

script:
    - yarn lint && yarn test

after_script:
    - send_cover

notifications:
    email: false
